---
- hosts: local
  connection: local
  tasks:
    - vsphere_guest:
        vcenter_hostname: vcenter ip
        username: vcenter username
        password: password
        guest: test-vm
        state: reconfigured
        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd:  yes
          notes: Reconnfiguring the test-vm
        vm_disk:
          disk1:
            size_gb: 2
            type: thin
            datastore: datastore name
        vm_nic:
          nic1:
            type: vmxnet3
            network: network name
            network_type: standard
        vm_hardware:
          memory_mb: 2048
          num_cpus: 2
          osid: centos64Guest
          scsi: paravirtual
        esxi:
          datacenter: datacenter name
          hostname: esxi host ip
        validate_certs: no
