---
- hosts: local
  connection: local
  tasks:
    - vsphere_guest:
        vcenter_hostname: 10.XXXXXX
        username: nsangadala
        password: xxxxx
        guest: windows-vm
        state: powered_on
        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd:  yes
          notes: This is a test windows-VM
        vm_disk:
          disk1:
            size_gb: 30
            type: thin
            datastore: Datastore name
        vm_nic:
          nic1:
            type: vmxnet3
            network: vlan name
            network_type: standard
        vm_hardware:
          memory_mb: 1024
          num_cpus: 1
          osid: windows7_64Guest
          scsi: paravirtual
          vm_cdrom:
            type: "iso" 
            iso_path: "ISO path"
        esxi:
          datacenter: HamiltonDR
          hostname: host-ipaddress
        validate_certs: no

